version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app .
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 160405506280.dkr.ecr.ap-south-1.amazonaws.com
      - run:
          name: Tag Docker image
          command: |
            docker tag my-app:latest 160405506280.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      - run:
          name: Push Docker image to ECR
          command: |
            docker push 160405506280.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push